In [1]:
%matplotlib inline

In [2]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b

loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [3]:
print('Gradient function for z =', z.grad_fn)
print('Gradient function for loss =', loss.grad_fn)

Gradient function for z = <AddBackward0 object at 0x7feed0f68160>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward object at 0x7feed0f68040>


In [4]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0667, 0.0494, 0.1931],
        [0.0667, 0.0494, 0.1931],
        [0.0667, 0.0494, 0.1931],
        [0.0667, 0.0494, 0.1931],
        [0.0667, 0.0494, 0.1931]])
tensor([0.0667, 0.0494, 0.1931])


# Disabling gradient tracking

In [5]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w) + b
print(z.requires_grad)

True
False


In [8]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

z_det = z.detach()
print(z_det.requires_grad)
print(z_det)

True
False
tensor([-1.3857, -1.7498,  0.3194])
