In [1]:
%matplotlib inline

In [2]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


*Import from data*

In [4]:
nparray = np.array(data)
print(nparray)

[[1 2]
 [3 4]]


In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5819, 0.4610],
        [0.0753, 0.6717]]) 



## Shape
define the shape of a tensor

In [ ]:
shape1 = (2,3,2,)
rand_shape1 = torch.rand(shape1)
print(f"Random Tensor with specified shape: \n {rand_shape1} \n")

## Properties of a tensor

Shape
datatype
device(?)

In [7]:
tensor_for_properties = torch.rand(3,4)
print(f"Shape: {tensor_for_properties.shape}")
print(f"Datatype: {tensor_for_properties.dtype}")
print(f"Device: {tensor_for_properties.device}")

Shape: torch.Size([3, 4])
Datatype: torch.float32
Device: cpu


Move large tensors between devices can be expensive

In [15]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [16]:
tensor = torch.rand(3,5)
print(tensor)
print("First row:", tensor[0,:])
print("First column:", tensor[:,0])
print("Last column:", tensor[:,-1])

# Modification to elements
tensor[:,1] = 0
print(tensor)

tensor([[0.1288, 0.7237, 0.8743, 0.6228, 0.3967],
        [0.2874, 0.8631, 0.4989, 0.4614, 0.9405],
        [0.7952, 0.7744, 0.5684, 0.7700, 0.4791]])
First row: tensor([0.1288, 0.7237, 0.8743, 0.6228, 0.3967])
First column: tensor([0.1288, 0.2874, 0.7952])
Last column: tensor([0.3967, 0.9405, 0.4791])
tensor([[0.1288, 0.0000, 0.8743, 0.6228, 0.3967],
        [0.2874, 0.0000, 0.4989, 0.4614, 0.9405],
        [0.7952, 0.0000, 0.5684, 0.7700, 0.4791]])


In [18]:
# Item
tensor = torch.rand(3,4)
agg = tensor.sum()
agg_item = agg.item()
print("This is agg:",agg,"\n This is itemized agg:",agg_item)


This is agg: tensor(4.1955) 
 This is itemized agg: 4.195498466491699


ValueError: only one element tensors can be converted to Python scalars

With NumPy:
From torch to numpy

In [20]:
tensor = torch.ones(5)
print(f"t: {tensor}")
numpy = tensor.numpy()
print(f"n: {numpy}")

tensor.add_(1)
print(f"n is modified, too: {numpy}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
n is modified, too: [2. 2. 2. 2. 2.]


With NumPy:
From numpy to torch

In [22]:
numpy = np.ones(5)
tensor = torch.from_numpy(numpy)
np.add(numpy,1,out=numpy)
print(f"tensor is modified, too:{tensor}")

tensor is modified, too:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
